name: Make Ready N Deploy
on: push
jobs:
  get-code:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install npm
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install deps
        run: npm ci
  make-ready:
    needs: get-code
    runs-on: ubuntu-latest
    steps:
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - name: deploy
        run: echo "DEPLOYING.."
